import { test, expect } from '@playwright/test';

test('Hamburger Menu Blur - Root Cause Analysis', async ({ page }) => {
  await page.goto('/--sdk');
  await page.waitForLoadState('networkidle');

  // Find and scroll to Hamburger Menu section, then enable blur via direct DOM manipulation
  // to ensure settings are applied

  // First, let's enable the menu blur via localStorage (the settings are stored there)
  await page.evaluate(() => {
    const settings = {
      backdropBlur: 'md',
      headerBlurEnabled: true,
      headerBlurUseColor: true,
      headerBlurOpacity: 85,
      menuBlurEnabled: true,  // ENABLE menu blur
      menuBlurIntensity: 'lg', // Set to 'lg'
      menuBlurUseColor: false, // Clear blur (no background color)
      menuBlurOpacity: 70,
    };
    localStorage.setItem('ai-saas-ui-settings', JSON.stringify(settings));
  });

  // Reload to apply settings
  await page.reload();
  await page.waitForLoadState('networkidle');

  // Screenshot initial state
  await page.screenshot({ path: 'blur-final-01-settings-applied.png' });
  console.log('Screenshot 1: Settings applied via localStorage');

  // Open the hamburger menu
  const menuButton = page.locator('button[aria-label="Open menu"]');
  await menuButton.click();
  await page.waitForTimeout(500);

  await page.screenshot({ path: 'blur-final-02-menu-open.png' });
  console.log('Screenshot 2: Menu opened');

  // Inspect the nav element
  const navDiagnosis = await page.evaluate(() => {
    const nav = document.querySelector('nav');
    if (!nav) return { error: 'No nav found' };

    const computed = window.getComputedStyle(nav);
    const classList = Array.from(nav.classList);

    return {
      classList,
      hasBackdropBlurClass: classList.some(c => c.includes('backdrop-blur')),
      backdropBlurClasses: classList.filter(c => c.includes('backdrop-blur')),
      computedBackdropFilter: computed.backdropFilter,
      computedBackground: computed.backgroundColor,
      inlineStyle: nav.getAttribute('style'),
      // Check for CSS property that might interfere
      overflow: computed.overflow,
      overflowY: computed.overflowY,
      isolation: computed.isolation,
      contain: computed.contain,
      willChange: computed.willChange,
    };
  });

  console.log('\n====== NAV DIAGNOSIS ======');
  console.log('Classes:', navDiagnosis.classList?.join(' '));
  console.log('Has backdrop-blur class:', navDiagnosis.hasBackdropBlurClass);
  console.log('Backdrop-blur classes:', navDiagnosis.backdropBlurClasses);
  console.log('Computed backdrop-filter:', navDiagnosis.computedBackdropFilter);
  console.log('Computed background:', navDiagnosis.computedBackground);
  console.log('Inline style:', navDiagnosis.inlineStyle);
  console.log('Overflow:', navDiagnosis.overflow);
  console.log('OverflowY:', navDiagnosis.overflowY);
  console.log('Isolation:', navDiagnosis.isolation);

  // Check parent elements for stacking context issues
  const parentDiagnosis = await page.evaluate(() => {
    const nav = document.querySelector('nav');
    if (!nav) return [];

    const results: { tag: string; computed: Record<string, string> }[] = [];
    let current = nav.parentElement;
    let depth = 0;

    while (current && depth < 5) {
      const computed = window.getComputedStyle(current);
      results.push({
        tag: `${current.tagName}.${current.className?.split(' ').slice(0, 2).join('.')}`,
        computed: {
          overflow: computed.overflow,
          position: computed.position,
          zIndex: computed.zIndex,
          isolation: computed.isolation,
        }
      });
      current = current.parentElement;
      depth++;
    }

    return results;
  });

  console.log('\n====== PARENT ELEMENTS ======');
  parentDiagnosis.forEach((p, i) => {
    console.log(`Parent ${i}: ${p.tag}`);
    console.log(`  overflow: ${p.computed.overflow}, position: ${p.computed.position}, zIndex: ${p.computed.zIndex}`);
  });

  // Check if the blur class is even being generated by looking at the DOM
  const blurClassCheck = await page.evaluate(() => {
    // Check if any element on the page has a backdrop-blur class applied
    const elementsWithBlur = document.querySelectorAll('[class*="backdrop-blur"]');
    return {
      count: elementsWithBlur.length,
      elements: Array.from(elementsWithBlur).map(el => ({
        tag: el.tagName,
        class: el.className,
      })).slice(0, 10)
    };
  });

  console.log('\n====== ELEMENTS WITH BACKDROP-BLUR CLASS ======');
  console.log(`Total count: ${blurClassCheck.count}`);
  blurClassCheck.elements.forEach(el => {
    console.log(`  ${el.tag}: ${el.class.slice(0, 100)}`);
  });

  // Now test with menuBlurUseColor = true
  await page.evaluate(() => {
    const settings = {
      backdropBlur: 'md',
      headerBlurEnabled: true,
      headerBlurUseColor: true,
      headerBlurOpacity: 85,
      menuBlurEnabled: true,
      menuBlurIntensity: 'lg',
      menuBlurUseColor: true, // Enable color behind blur
      menuBlurOpacity: 50,    // 50% opacity
    };
    localStorage.setItem('ai-saas-ui-settings', JSON.stringify(settings));
  });

  await page.reload();
  await page.waitForLoadState('networkidle');

  // Open menu again
  await page.locator('button[aria-label="Open menu"]').click();
  await page.waitForTimeout(500);

  await page.screenshot({ path: 'blur-final-03-with-color.png' });
  console.log('\nScreenshot 3: Menu with color behind blur');

  const navWithColor = await page.evaluate(() => {
    const nav = document.querySelector('nav');
    if (!nav) return null;
    const computed = window.getComputedStyle(nav);
    return {
      classList: Array.from(nav.classList),
      backdropFilter: computed.backdropFilter,
      backgroundColor: computed.backgroundColor,
      inlineStyle: nav.getAttribute('style'),
    };
  });

  console.log('\n====== NAV WITH USE COLOUR ENABLED ======');
  console.log('Classes:', navWithColor?.classList?.join(' '));
  console.log('Backdrop-filter:', navWithColor?.backdropFilter);
  console.log('Background:', navWithColor?.backgroundColor);
  console.log('Inline style:', navWithColor?.inlineStyle);

  // Final diagnosis
  console.log('\n====== ROOT CAUSE ANALYSIS ======');

  if (!navDiagnosis.hasBackdropBlurClass) {
    console.log('ISSUE: The backdrop-blur-lg class is NOT being applied to the nav element.');
    console.log('The getMenuBlurClass() function should return "backdrop-blur-lg" but the class is missing from the DOM.');
  } else if (navDiagnosis.computedBackdropFilter === 'none') {
    console.log('ISSUE: The backdrop-blur class IS present, but computed backdrop-filter is "none".');
    console.log('Possible causes:');
    console.log('  1. overflow-y-auto on nav or parent creates new stacking context that breaks backdrop-filter');
    console.log('  2. The class might be getting overridden by another style');
    console.log('  3. Browser compatibility issue');
  }
});
